trigger:
  - "*"

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: "Release"
  outputDir: "$(Build.ArtifactStagingDirectory)/$(buildConfiguration)"

steps:
  # Manually install JDK (Java Development Kit) version 17
  - script: |
      sudo apt-get update
      sudo apt-get install -y openjdk-17-jdk
    displayName: "Install OpenJDK 17"

  # Restore Maven dependencies
  - task: Maven@4
    displayName: "Maven - Restore Dependencies"
    inputs:
      mavenPomFile: "pom.xml" # Path to the pom.xml file
      goals: "dependency:resolve"

  # Build the Maven project
  - task: Maven@4
    displayName: "Maven - Build"
    inputs:
      mavenPomFile: "pom.xml" # Path to the pom.xml file
      goals: "clean install"

  # Run unit tests
  - task: Maven@4
    displayName: "Maven - Run Tests"
    inputs:
      mavenPomFile: "pom.xml" # Path to the pom.xml file
      goals: "test"

  # Publish the project to the output directory
  - task: Maven@4
    displayName: "Maven - Package"
    inputs:
      mavenPomFile: "pom.xml"
      goals: "package"
      options: "-DoutputDirectory=$(outputDir)"
  
  # Compress the output directory into a ZIP file
  - script: |
      zip -r $(outputDir)/artifact.zip $(outputDir)
    displayName: "Create ZIP File of Build Artifacts"

  # Publish the ZIP file as an artifact
  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact: drop"
    inputs:
      pathtoPublish: "$(outputDir)/artifact.zip"
      artifactName: "drop"
      publishLocation: "Container"
    condition: succeeded()
