trigger:
  - "*"

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: "Release"

steps:
  # Manually install JDK (Java Development Kit) version 17
  - script: |
      sudo apt-get update
      sudo apt-get install -y openjdk-19-jdk
    displayName: "Install OpenJDK 19"

  # Restore Maven dependencies
  - task: Maven@4
    displayName: "Maven - Restore Dependencies"
    inputs:
      mavenPomFile: "pom.xml" # Path to the pom.xml file
      goals: "dependency:resolve"

  # Build the Maven project
  - task: Maven@4
    displayName: "Maven - Build"
    inputs:
      mavenPomFile: "pom.xml" # Path to the pom.xml file
      goals: "clean install"

  # Run unit tests
  - task: Maven@4
    displayName: 'Run unit tests - $(buildConfiguration)'
    inputs:
      mavenPomFile: "pom.xml"
      goals: "test"
      options: "-DskipTests=false"

  # Publish test results
  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    inputs:
      testResultsFiles: '**/target/surefire-reports/*.xml'
      mergeTestResults: true

  # Compress the contents of the target directory into a ZIP file
  - script: |
      zip -r $(Build.ArtifactStagingDirectory)/artifact.zip $(System.DefaultWorkingDirectory)/target
    displayName: "Create ZIP File of Build Artifacts"

  # Publish the ZIP file as an artifact
  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifacts"
    inputs:
      pathtoPublish: "$(Build.ArtifactStagingDirectory)/artifact.zip"
      artifactName: "drop"
      publishLocation: "Container"
      condition: succeeded()
