trigger:
  - "*"

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: "Release"

steps:
  # Install JDK (Java Development Kit)
  - task: UseJavaVersion@1
    inputs:
      versionSpec: "11" # Specify the JDK version you need, e.g., '8', '11', etc.
      jdkArchitectureOption: "x64"

  # Restore Maven dependencies
  - task: Maven@4
    displayName: "Maven - Restore Dependencies"
    inputs:
      mavenPomFile: "pom.xml" # Path to the pom.xml file
      goals: "dependency:resolve"

  # Build the Maven project
  - task: Maven@4
    displayName: "Maven - Build"
    inputs:
      mavenPomFile: "pom.xml" # Path to the pom.xml file
      goals: "clean install"

  # Run unit tests
  - task: Maven@4
    displayName: "Maven - Run Tests"
    inputs:
      mavenPomFile: "pom.xml" # Path to the pom.xml file
      goals: "test"

  # Archive build artifacts (optional)
  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifacts"
    inputs:
      pathtoPublish: "$(System.DefaultWorkingDirectory)/target"
      artifactName: "drop"
      publishLocation: "Container"
